QCC=fteqcc

all:
	mkdir -p ../../progs/
	$(QCC) $(CFLAGS) -I../../../src/server deathmatch.qc 
	$(QCC) $(CFLAGS) -I../../../src/server singleplayer.qc
	$(QCC) $(CFLAGS) -I../../../src/server invasion.qc
