name: Manual-Build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: docker

    steps:
    - name: clone nuclide
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: vera/nuclide
        ref: current

    - name: clone game
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        path: "./${{ github.event.repository.name }}"

    - name: add pkg zip
      run: |
        apt update
        apt install -y \
        zip

    - name: set env
      run: echo "PAKTAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: build pak
      run: make dist-pak NAME=bin GAME=${{ github.event.repository.name }}

    - name: upload log artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-log
        path: ./build/bin-content.log

    - name: upload pak
      uses: actions/forgejo-release@v2
      with:
        url: https://code.idtech.space
        repo: "${{ github.repository }}"
        tag: "${{ env.PAKTAG }}"
        sha: "${{ github.sha }}"
        direction: upload
        release-dir: ./build/bin-content/${{ github.event.repository.name }}/
        token: ${{ secrets.TOKEN }}
        title: "Manual Build"
        prerelease: false
        override: true
        release-notes-assistant: true
