name: pk4

on: push

jobs:
  build:
    runs-on: docker

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: vera/nuclide
        ref: Develop

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        ref: Develop
        path: "./${{ github.event.repository.name }}"

    - name: apt install zip
      run: |
        apt update
        apt install -y \
        zip

    - name: assemble pk4
      run: make dist-pak NAME=bin GAME=${{ github.event.repository.name }}

    - uses: actions/upload-artifact@v3
      with:
        name: build-log
        path: ./build/bin-content.log

    - uses: actions/forgejo-release@v2
      with:
        url: https://code.idtech.space
        repo: "${{ github.repository }}"
        direction: upload
        release-dir: ./build/bin-content/${{ github.event.repository.name }}/
        token: ${{ secrets.TOKEN }}
