/*
 * Copyright (c) 2016-2020 Marco Hladik <marco@icculus.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
 * IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
 * OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

enum
{
	ANIM_LOOKIDLE,
	ANIM_IDLE,
	ANIM_DEEPIDLE,
	ANIM_RUN2,
	ANIM_WALK2HANDED,
	ANIM_2HANDSHOT,
	ANIM_CRAWL,
	ANIM_CROUCHIDLE,
	ANIM_JUMP,
	ANIM_LONGJUMP,
	ANIM_SWIM,
	ANIM_TREADWATER,
	ANIM_RUN,
	ANIM_WALK,
	ANIM_AIM2,
	ANIM_SHOOT2,
	ANIM_AIM1,
	ANIM_SHOOT1,
	ANIM_DIESIMPLE,
	ANIM_DIEBACKWARDS1,
	ANIM_DIEBACKWARDS2,
	ANIM_DIEFORWARD,
	ANIM_DIEHEADSHOT,
	ANIM_DIESPIN,
	ANIM_DIEGUTSHOT,
	ANIM_AIMCROWBAR,
	ANIM_SHOOTCROWBAR,
	ANIM_CR_AIMCROWBAR,
	ANIM_CR_SHOOTCROWBAR,
	ANIM_AIMTRIPMINE,
	ANIM_SHOOTTRIPMINE,
	ANIM_CR_AIMTRIPMINE,
	ANIM_CR_SHOOTTRIPMINE,
	ANIM_AIM1HAND,
	ANIM_SHOOT1HAND,
	ANIM_CR_AIM1HAND,
	ANIM_CR_SHOOT1HAND,
	ANIM_AIMPYTHON,
	ANIM_SHOOTPYTHON,
	ANIM_CR_AIMPYTHON,
	ANIM_CR_SHOOTPYTHON,
	ANIM_AIMSHOTGUN,
	ANIM_SHOOTSHOTGUN,
	ANIM_CR_AIMSHOTGUN,
	ANIM_CR_SHOOTSHOTGUN,
	ANIM_AIMGAUSS,
	ANIM_SHOOTGAUSS,
	ANIM_CR_AIMGAUSS,
	ANIM_CR_SHOOTGAUSS,
	ANIM_AIMMP5,
	ANIM_SHOOTMP5,
	ANIM_CR_AIMMP5,
	ANIM_CR_SHOOTMP5,
	ANIM_AIMRPG,
	ANIM_SHOOTRPG,
	ANIM_CR_AIMRPG,
	ANIM_CR_SHOOTRPG,
	ANIM_AIMEGON,
	ANIM_SHOOTEGON,
	ANIM_CR_AIMEGON,
	ANIM_CR_SHOOTEGON,
	ANIM_AIMSQUEAK,
	ANIM_SHOOTSQUEAK,
	ANIM_CR_AIMSQUEAK,
	ANIM_CR_SHOOTSQUEAK,
	ANIM_AIMHIVE,
	ANIM_SHOOTHIVE,
	ANIM_CR_AIMHIVE,
	ANIM_CR_SHOOTHIVE,
	ANIM_AIMBOW,
	ANIM_SHOOTBOW,
	ANIM_CR_AIMBOW,
	ANIM_CR_SHOOTBOW
};

void Animation_PlayerTop(float);
void Animation_PlayerTopTemp(float, float);
